spring.application.name=logistics-dispatch-system

spring.profiles.active=prod

spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=${DB_DRIVER}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true

spring.flyway.enabled=true

jwt.secret-key=${JWT_SECRET_KEY}
jwt.access-expiration-time=${JWT_ACCESS_EXPIRATION_TIME}
jwt.refresh-expiration-time=${JWT_REFRESH_EXPIRATION_TIME}

app.webhooks.logistics-event-url=${WEBHOOK_LOGISTICS_EVENT_URL}